In [17]:
import pandas as pd
import numpy as np

In [18]:
df=pd.read_csv('house_data.csv')
df

length  breadth  house_price  room_size
0     150    240.0     250000.0          2
1     200    100.0          NaN          1
2     300      NaN     200000.0          3

In [19]:
df.shape

(3, 4)

In [20]:
x=df[['length','breadth','room_size']].values  #independent variables

In [21]:
y=df[['house_price']].values  #dependent variables

In [22]:
from sklearn.impute import SimpleImputer

In [23]:
#FINDING MISSING VALUES AND HANDLE THEM

In [24]:
df.isnull().sum()

length         0
breadth        1
house_price    1
room_size      0
dtype: int64

In [25]:
df.dropna(inplace=True)
df

length  breadth  house_price  room_size
0     150    240.0     250000.0          2

In [27]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(x[:,1:3])
x

array([[150., 240.,   2.],
       [200., 100.,   1.],
       [300.,  nan,   3.]])

In [28]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [30]:
#encoding categorical data
from sklearn.preprocessing import LabelEncoder

In [32]:
l_e_x=LabelEncoder()
l_e_y=LabelEncoder()
x[:,0]=l_e_x.fit_transform(x[:,0])
y=l_e_y.fit_transform(y)

C:\Users\VK\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [35]:
#splitting dataset into training dataset and testing dataset
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [37]:
#feature scaling
from sklearn.preprocessing import StandardScaler

In [40]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
print(x_train,"\n","\n",x_test)

[[ 1.  1.  1.]
 [-1. -1. -1.]] 
 
 [[0. 0. 0.]]
